name: # Name of the Catalog Entry
description: >
  A Demo App which does almost nothing of any practical value.
  # Description of the Catalog Entry
version: 0.0.1-rancher1# Version of the Catalog to be used
category: Toy Apps# Category to be used for searching catalog entries
maintainer: Natalya# The maintainer of the catalog entry
license: Apache2# The license
projectURL: https://github.com/Natalyas/rancher.git # A URL related to the catalog entry
